package sdn

import compiler.AST.{Call2, Fundef2}
import compiler.ASTL.{sym, transfer}
import compiler.ASTLfun._
import compiler.{AST, ASTB, ASTBfun, ASTBt, ASTLfun, B, E, Locus, Ring, T, V, repr}
import compiler.SpatialType.{BoolE, BoolEv, BoolV, BoolVe, UintVx}
import dataStruc.{BranchNamed, Named}
import progOfmacros.Comm.neighborsSym
import progOfmacros.Wrapper.{borderS, exist}
import progOfmacros.RedT.{clock2, shrink2min1to5}
import progOfmacros.Wrapper
import sdn.Globals.root4naming
import sdn.Rand
import sdn.Util.addSym

import scala.util.matching.Regex.Match

/** adds the possibility of using a randomizer */
trait rando {
  val _rand = new Rand()  // Champ privé
  def rand: Rand = _rand  // Getter public pour le champ
}

/**
 * MoveC is a "centered move". It means that it is defined within the body support.
 * It can  encodes a move on V-agents, but also Ve agents.
 */
abstract class MoveC extends Named with BranchNamed {
  /**
   * @param that another move to combine with this move
   * @return a move that represents the combined effect of this move and that move
   */
  def | (that: MoveC): MoveC

  /**
   * @param cond
   * @return a move that is the result of applying the condition `cond` to this move, effectively restricting its effect to where `cond` is true
   */
  def restrict(cond:BoolV): MoveC

  /** true if the move has any effect (either yes or no) */
  val triggered: BoolV

  /** when computing push, we selected maxprio only among the yes, we do not consider the no */
  val triggeredYes: BoolV

  /**
   * This method computes the effective flips caused by the move, taking into account both withdrawals and pushes.
   * It should return true for vertices that would change state due to the move, and false for those that remain unchanged.
   *
   * @param is the current state of the agent's support
   * @return a boolean field indicating where the move would cause flips (true for vertices that would flip)
   */
  def move2flip(is: BoolV): BoolV

  /** should remain false */
  val bug: BoolV
}

/**
 * @param empty where to withdraw at
 * @param push  where to extends towards
 * centered move with only yes
 */
case class MoveC1 (val empty: BoolV, val push: BoolVe) extends MoveC{
  override def | (that: MoveC):MoveC = that match{
    case mc1:MoveC1=>MoveC1(empty|mc1.empty,push|mc1.push)
    case mc2:MoveC2=> mc2 | this
  }

  override def restrict(cond: BoolV) = MoveC1(empty & cond, push & e(cond))

  /**
   * Inflects the move by probabilistically reducing withdrawals and pushes in areas related to the target.
   *
   * @param target Region affected by the move
   * @param rand Random boolean field used to soften the move
   * @return a new MoveC1 with inflected empty and push fields
   */
  def inflechi(target: BoolV, rand: BoolV) =
    MoveC1(
      empty & (~target|rand),
      push & ( e(rand) | neighborsSym(e(target)) )
    )

  /**
   * Convert push to a boolV, true for vertice pointed by one of the push.
   *
   * @note There can be several distinct push to the same single vertice, it is sufficient that there is one.
   */
  val invade = exist(neighborsSym(push))

  /** triggered if there is either a withdrawal or a push */
  val triggered = empty | invade
  val triggeredYes: BoolV = triggered

  override def move2flip(isV: BoolV): BoolV = cond(isV,empty,invade)

  val bug = empty & invade
}

/**
 * A centered move can take into account the fact that we can force no change
 * @param yes for setting flip
 * @param no for specifying absence of flip, using either no.push or no.Empty
 */
case class MoveC2(val yes:MoveC1,val no:MoveC1) extends MoveC{
  def | (that: MoveC):MoveC = that match {
    case mc2:MoveC2=> MoveC2((yes|mc2.yes).asInstanceOf[MoveC1],(no|mc2.no).asInstanceOf[MoveC1] )
    case mc1:MoveC1=> MoveC2((yes|mc1).asInstanceOf[MoveC1],no )  //moveC1 are considered to be yesMove by default.
  }

  override def restrict(cond: BoolV) = MoveC2(yes.restrict(cond), no.restrict(cond))

  /** True if the move has any effect, either in the yes or no part. */
  val triggered = yes.triggered | no.triggered

  val bug = yes.triggered & no.triggered | yes.bug | no.bug

  /** True if the move has a positive effect (yes part is triggered). */
  val triggeredYes: BoolV = yes.triggered

  /** Computes the effective flips caused by the move, taking into account both the "yes" and "no" components. */
  def move2flip(isV: BoolV): BoolV = yes.move2flip(isV) & ~no.move2flip(isV)
}

object MoveC{
  def empty(where:BoolV)=MoveC1(where,  e(root4naming.myFalse))
  def push(where:BoolVe)=MoveC1(root4naming.myFalse, where)
}
/**
 * A force acts on an agent support and generates a centered movement proposal.
 *
 * Forces are composable with:<br>
 * - `|` to merge movement proposals,<br>
 * - [[inflechi]] to probabilistically soften withdrawals toward a target region.
 */
abstract class Force extends  Named {
  /**
   * @param ag movable agent receiving the force
   * @return a move generated by this force for a movable agent of type `MovableAgV`
   *
   * @note This method should be overridden by concrete force implementations that support `MovableAgV` agents.
   */
  def actionV(ag:MovableAgV): MoveC = {
    assert(false,"force "+name+"undefined on Vagent")
    null
  }

  //def actionVe(ag:VeAg): MoveC={assert(false,"force "+name+"undefined on Veagent");null}
  /**
   * Computes the movement generated by this force for a movable agent of any supported locus.
   *
   * Dispatch is done by runtime locus matching.
   *
   * @param ag movable agent receiving the force
   * @return an agent-centered move
   */
  def action (ag: MovableAg[_<:Locus]): MoveC=
    ag.locus match {
    case V() => actionV(ag.asInstanceOf[MovableAgV])
   // case T(V(),E()) => actionVe(ag.asInstanceOf[MovAgVe])
  }

  /**
   * Combines two forces into a single force.
   *
   * The resulting force evaluates both operands and merges their moves using `MoveC.|`.
   *
   * @param that force to combine with this force
   * @return composite force equivalent to applying both forces then OR-merging results
   */
  def | (that: Force)= {
    val myThis=this
    new Force {
      override def actionV(ag: MovableAgV): MoveC =  myThis.actionV(ag) | that.actionV(ag)
    }
  }

  /**
   * Builds a probabilistically softened variant of this force toward a target region.
   *
   * This helper currently assumes the underlying move is a [[MoveC1]]. It injects random bits to
   * reduce withdrawals/pushes in target-related areas.
   *
   * @param target target region used to bias random softening
   * @return derived force with stochastic inflection
   */
  def inflechi(target:BoolV): Force = {
    val myThis=this
    val rnd1 = root4naming.addRandBit().asInstanceOf[BoolV]
    val rnd2 = root4naming.addRandBit().asInstanceOf[BoolV]
    val rnd3 = root4naming.addRandBit().asInstanceOf[BoolV]
    new Force {
      override def actionV(ag: MovableAgV): MoveC =
        myThis.actionV(ag).asInstanceOf[MoveC1].inflechi(rnd1 & rnd2 & rnd3, target) //marche seulement si le move est un moveC1
    }
  }
}



object Force{
  /**
   * Restricts a force to a boolean condition.
   *
   * @param f force to restrict
   * @param b restricting condition; should be uniform where the force is exerted
   * @return force whose generated move is conditionally restricted
   */
  def restrictF(f:Force,b:BoolV)=new Force {
    override def actionV(ag: MovableAgV): MoveC =  f.actionV(ag).restrict(b)
  }

  import MoveC._
  /**
   * Force that proposes maximal movement everywhere possible on the support.
   *
   * It empties occupied vertices and pushes into all allowed border directions.
   * Random priority bits then resolve effective choice in arbitration steps.
   */
  val total:Force=new Force(){
    override def actionV(ag: MovableAgV): MoveC = MoveC1(ag.muis,ag.bf.brdVeIn)//extends and empties everywhere possible.
  }
  /**
   * Builds a targeting force that drives occupancy toward a desired region.
   *
   * @param cible target region the particle should fill
   * @return force encouraging expansion to `cible` and withdrawal elsewhere when reachable
   */
  def cibler(cible:BoolV):Force=new Force{
    val toCible=neighborsSym(e(cible))
    /** true if there is a target in the immediate neighborhood */
    val next2cible=exist(toCible)
    override def actionV(ag: MovableAgV): MoveC = {
      //we empty non-target and forbid moving towards non-target, only if target is reachable, so as to avoid blocking situation
      MoveC2(MoveC1(~cible & next2cible ,toCible & ag.bf.brdVeIn),MoveC1(cible, ~(toCible&e(next2cible))& ag.bf.brdVeIn ))
    }
  }

  /**
   * Builds a stabilizing negative force used to cancel lower-priority movement.
   *
   * @param stbl stability condition (true where lower priorities should be canceled)
   * @return force generating "no" moves to promote convergence
   */
  def stabilize(stbl: BoolV): Force = new Force() {
    override def actionV(ag: MovableAgV): MoveC = {
      val yes = MoveC1(root4naming.myFalse, e(root4naming.myFalse)) //force is pure negative
      /** if stable2 , this will cancel movement of lower priority, */
      val no = MoveC1(stbl, e(stbl) & ag.bf.brdVeIn) // negative  forces
      MoveC2(yes,no)
    }
  }

/*
  val emptyZgt=(isV&zgt.muis) & exist(neighborsSym(e(isV & ~(zgt.muis))))
  val emptyZlt= (isV& ~zlt.muis) & exist(neighborsSym(e(isV & (zlt.muis))))
  val pushZlt=shrink2min1to5(neighborsSym(e(zlt.muis)))
  val pushZgt=shrink2min1to5(neighborsSym(e(~zgt.muis)))
*/

  /**
   * Builds a repulsion force guided by a propagated "greater radius" zone signal.
   *
   * @param zoneGt signal from nearest Gabriel centers; true where adjacent Voronoi is bigger
   * @return force pushing particles away from larger neighboring Voronoi regions
   */
  def repulsePropagate(zoneGt: BoolV): Force = new Force{
    override def actionV(ag: MovableAgV): MoveC = {
      //emptying applies on tripleton or doubleton, on vertice inside zoneGt having neighbor vertices outside
      MoveC1(ag.muis & zoneGt & exist(neighborsSym(e(ag.muis & ~zoneGt))),
        shrink2min1to5(neighborsSym(e(~zoneGt)))) //we fill by looking "most away as possible" from zoneGt
    }
  }
  /**
   * Builds an attraction force guided by a propagated "smaller radius" zone signal.
   *
   * @param zoneLt signal from nearest Gabriel centers; true where adjacent Voronoi is smaller
   * @return force moving particles toward smaller neighboring Voronoi regions
   */
  def attractPropagate(zoneLt:BoolV):Force = new Force{
    override def actionV(ag: MovableAgV): MoveC = {
      //emptying applies on tripleton or doubleton, on vertice outside zoneLt having neighbor vertices inside
      MoveC1( ag.muis & ~ zoneLt & exist(neighborsSym(e(ag.muis &  zoneLt))),
        shrink2min1to5(neighborsSym(e(zoneLt)))) //we fill by looking "most towards as possible to zoneLt
    }
  }

  /**
   * Density-guided force favoring occupancy of Voronoi high-density summit areas.
   *
   * The generated move promotes expansion toward denser neighbors while forbidding
   * some low-value expansions, using a mixed positive/negative move (`MoveC2`).
   *
   * @param density local density descriptor
   * @return force steering movement according to density gradients
   */
  def seizeSummitDensity(density:UintVx)=new Force{
    override def actionV(ag:MovableAgV): MoveC= {
      val hasNearer: BoolV = exist(transfer( density.lt) & neighborsSym(e(ag.muis)))
      val hasFurther = Wrapper.exist(transfer( density.gt) & neighborsSym(e(ag.muis)))
      val notDense = density < fromInt(3)
      val notDenseN = addSym(e(notDense))
      val oui=MoveC1( ag.muis & hasFurther & ~hasNearer & notDense, //on vide si y a des plus loin, pas de plus pres,
        // et si on n'est pas dense
        transfer(density.gt)& ag.bf.brdVeIn) //on envahit des voisines plus dense OK
      //on va toujours remplir un vertice dont la densité est plus grande
      //pour cibler des particules tripleton,
      // on peut ou on peut ne pas autoriser  de vider si nombre de voisin est   3

      val non = MoveC1(ag.muis & ~hasFurther,  //on interdit de vider si y a pas de plus dense a coté
        transfer( density.lt)  & ag.bf.brdVeIn & notDenseN.sym ) //on interdit d'envahir des moins dense qui de plus ne sont pas dense
      //on ne vas pas non plus chercher a remplir un vertice sommet voisin de dentisté pluc petite, si celle ci est  <3
      MoveC2(oui, non)
    }
  }


  /** we designed a random move that does not break the quasipoint property,
   * eliminating the need for checking gate-expensive mutex
   * However, we must still check for directionnality using
   * sophisticated blob tests, because combination with other force may break directionality
   * therefore, it is not usefull, finally
  val qpointRand: Force = new Force() with rando  {
    override def actionV(is: BoolV): MoveC = {
      val isqp = is.asInstanceOf[BoolV with QPointify] //this force works only on quasiPoint
      val extend12dir: BoolVe = e(isqp.singleton) & r.randDir //isolated point move toward one of the 12 possible directions
      val extend2side: BoolVe = clock2(transfer(sym(v(isqp.doubleton) & r.randSide)))
      MoveC1(false,extend2side | extend12dir) //ici on fait un or sur des boolVe
    }
  }*/
}
